### PR TITLE
enh: remove workaround for https://github.com/jakartaee/data/issues/361

### PR DESCRIPTION
**Pull request by lprimak**
fixes https://github.com/jakartaee/data/issues/361

### CODE REVIEW

**Comment by lprimak** [comment]
Jakarta Data M2 that has this fix has been released. This PR can be merged now @ivargrimstad

**Comment by lprimak** [comment]
M2 is now released. I will fix the conflicts in a minute :)

**Comment by lprimak** [comment]
Conflicts resolved

**Comment by arjantijms** [comment]
If Jakarta Data already released its M2, what will it release for Jakarta EE M2? Maybe M1.1 was a better name for an updated M1?

**Comment by ivargrimstad** [comment]
> If Jakarta Data already released its M2, what will it release for Jakarta EE M2? Maybe M1.1 was a better name for an updated M1?

It will be added to the M2 of Jakarta EE 11

**Comment by lprimak** [comment]
Since Jakarta Data M3 was released, I updated this PR to use that.
Time to merge?

**Pull request merged**
