### PR TITLE
shipping all platform JARs as empty JARs

### LINKED ISSUE #133: Regression: EE 10 Platform API JARs include transitive dependencies to Spec API JARs leading to duplicate classes
**Describe the bug**
This is a regression from Jakarta EE 8 (possibly 9)

Platform API JARs should not include the Spec JARs as transitive dependencies, as seen below.
The leads to duplicate classes on the classpath and problems
if an application uses has JPMS `module-info` anywhere (split package issues)
```
% mvnd dependency:tree
[INFO] --- maven-dependency-plugin:3.4.0:tree (default-cli) @ hope-website ---
[INFO] +- jakarta.platform:jakarta.jakartaee-api:jar:10.0.0:provided
[INFO] |  +- jakarta.platform:jakarta.jakartaee-web-api:jar:10.0.0:provided
[INFO] |  |  +- jakarta.servlet:jakarta.servlet-api:jar:6.0.0:provided
[INFO] |  |  +- jakarta.servlet.jsp:jakarta.servlet.jsp-api:jar:3.1.0:provided
[INFO] |  |  +- jakarta.el:jakarta.el-api:jar:5.0.1:provided
[INFO] |  |  +- jakarta.servlet.jsp.jstl:jakarta.servlet.jsp.jstl-api:jar:3.0.0:provided
[INFO] |  |  +- jakarta.faces:jakarta.faces-api:jar:4.0.1:provided
[INFO] |  |  +- jakarta.websocket:jakarta.websocket-api:jar:2.1.0:provided
[INFO] |  |  +- jakarta.websocket:jakarta.websocket-client-api:jar:2.1.0:provided
[INFO] |  |  +- jakarta.ejb:jakarta.ejb-api:jar:4.0.1:provided
[INFO] |  |  +- jakarta.transaction:jakarta.transaction-api:jar:2.0.1:provided
[INFO] |  |  +- jakarta.persistence:jakarta.persistence-api:jar:3.1.0:provided
[INFO] |  |  +- jakarta.validation:jakarta.validation-api:jar:3.0.2:provided
[INFO] |  |  +- jakarta.interceptor:jakarta.interceptor-api:jar:2.1.0:provided
[INFO] |  |  +- jakarta.enterprise:jakarta.enterprise.lang-model:jar:4.0.1:provided
[INFO] |  |  +- jakarta.inject:jakarta.inject-api:jar:2.0.1:provided
[INFO] |  |  +- jakarta.authentication:jakarta.authentication-api:jar:3.0.0:provided
[INFO] |  |  \- jakarta.security.enterprise:jakarta.security.enterprise-api:jar:3.0.0:provided
[INFO] |  +- jakarta.jms:jakarta.jms-api:jar:3.1.0:provided
[INFO] |  +- jakarta.activation:jakarta.activation-api:jar:1.2.2:provided
[INFO] |  +- jakarta.mail:jakarta.mail-api:jar:2.1.0:provided
[INFO] |  +- jakarta.resource:jakarta.resource-api:jar:2.1.0:provided
[INFO] |  +- jakarta.authorization:jakarta.authorization-api:jar:2.1.0:provided
[INFO] |  \- jakarta.batch:jakarta.batch-api:jar:2.1.1:provided
```

**To Reproduce**
```
        <dependency>
            <groupId>jakarta.platform</groupId>
            <artifactId>jakarta.jakartaee-api</artifactId>
            <version>10.0.0</version>
            <scope>provided</scope>
        </dependency>
```

**Workaround**
The issue can be worked around by excluding all transitive dependencies:
```
        <dependency>
            <groupId>jakarta.platform</groupId>
            <artifactId>jakarta.jakartaee-api</artifactId>
            <version>10.0.0</version>
            <scope>provided</scope>
            <exclusions>
                <exclusion>
                    <groupId>*</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

**Possible Solution**
I think you can make the Spic JARs `<optional>true</optional>` to solve this problem
Currently, it is set to false, not sure what's the reason for that.

### PR DESCRIPTION
**Pull request by lprimak**
Avoids duplicate class files and fixes OSGi and JPMS issues
fixes #133

### CODE REVIEW

**Comment by starksm64** [comment]
Look good to me. I did some basic compile testing of the generated empty jars and it works.

**Comment by lprimak** [comment]
Thanks! I just tested in my environment and it also works!

**Comment by lprimak** [comment]
Time to merge (and release?)

**Comment by lprimak** [comment]
Time to merge (and release?)

**Comment by OndroMih** [comment]
I think this will break javadoc generation for Jakarta EE platform and profiles.

I assume that javadocs are generated with `mvn javadoc:aggregate`. If I run it before this PR, this goal runs everything until the `compile` phase, including `glassfishbuild-maven-plugin:3.2.28:unpack-sources` and ` maven-resources-plugin:2.4.3:copy-resources`. Sources and resources from dependencies are used to generate the aggregate javadocs in `target/site/apidocs`. With this PR, this doesn't happen and aggregate Javadocs in `target/site/apidocs` are empty.

**Comment by OndroMih** [comment]
Instead of the changes in this PR, it should be enough to modify the parent pom with the following changes: https://github.com/OndroMih/jakartaee-api/commit/9b56052701b67e072f9da909a3d0f58aebf90494

**Comment by lprimak** [comment]
Or I can just port your changes into mine if you prefer

**Comment by lprimak** [comment]
I found an  issue with javadoc, I will fix it and combine our solutions into a the existing PR

**Comment by OndroMih** [comment]
Thanks, @lprimak. Now it looks good to me.

**Comment by Emily-Jiang** [comment]
Would this break the current apps that compile against the platform jars but now it is empty?

**Comment by lprimak** [comment]
> Would this break the current apps that compile against the platform jars but now it is empty?

Absolutely not, since they will still have maven dependencies on the spec JARs.
The only way I can see anything breaking is if the umbrella JARs are manually copied and used on the CLASSPATH, i.e. copied into tomcat/lib or something similar.

**Pull request merged**
